In [4]:
# Exercise 1 : Create a NumPy array of integers from 1 to 10.
import numpy as np
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [72]:
# Exercise 2: Create a 3x3 NumPy array filled with zeros.
A = np.zeros((3,3), dtype=int)
print(A)
A.dtype
print(np.zeros((3,3), dtype=np.int16))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [70]:
# Exercise 3: Create a NumPy array of 10 evenly spaced numbers between 0 and 5.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [30]:
# Exercise 4 : Create a 5x5 identity matrix using NumPy.
print(np.eye(5,5)) # = np.eye(5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [86]:
# Exercise 5 Create a 4x4 matrix with random values between 0 and 1.
np.random.seed(10)
print(np.random.random((4,4)))
print("-"*50)
print(np.random.rand(4,4))

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]
--------------------------------------------------
[[0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824]
 [0.65039718 0.60103895 0.8052232  0.52164715]]


In [48]:
# Exercise 6: Find the shape of a NumPy array.
A = np.random.random((4,4))
print(A.shape)

(4, 4)


In [54]:
# Exercise 7 : Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.
B=np.arange(16)
B.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [527]:
# Exercise 8: Find the data type of the elements in a NumPy array.
print(A.dtype)

int32


In [112]:
# Exercise 9: Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.
A= np.arange(1,100)
print(x for x in np.arange(1,101) if x%2 == 0)

<generator object <genexpr> at 0x00000210525C57D0>


In [98]:
# Exercise 10: Generate a 6x6 matrix of random integers between 10 and 50.
A = np.random.randint(10,50,(6,6))
print(A)

[[17 34 49 25 16 19]
 [10 14 24 14 16 19]
 [46 36 48 30 19 26]
 [21 49 27 49 43 21]
 [24 25 31 15 23 13]
 [41 22 33 27 39 15]]


In [104]:
# Exercise 11: lice a 2D NumPy array to extract a submatrix.
B = A[1:3,2:5]
B

array([[24, 14, 16],
       [48, 30, 19]])

In [118]:
# Exercise 12: Calculate the sum of all elements in a NumPy array.
sum(A)
#or sum(sum(A))

4950

In [144]:
# Exercise 13: Calculate the mean, median, and standard deviation of a NumPy array.
np.mean(A)
np.median(A)
np.std(A)

28.577380332470412

In [150]:
# Exercise 14: Find the maximum and minimum values in a NumPy array.
min(A)
max(A)

99

In [280]:
# Exercise 15 Create a NumPy array of 20 random integers and find the index of the maximum value.
A = np.random.randint(100, size=20)
print(np.argmax(A))

16


In [290]:
# Exercise 16 Create a NumPy array and reverse its elements.
A[:-1]

array([19,  0, 20, 28, 23, 89, 58, 71, 68, 82, 22, 71, 52, 89, 25, 80, 95,
       39, 21])

In [411]:
# Exercise 17
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])
print(A * B)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [409]:
# Exercise 18
print(np.diag(np.array([1, 2, 3])))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [413]:
# Exercise 19
C = np.array([[1, 0], [0, 1]])
D = np.array([[4, 1], [2, 2]])
print(np.dot(C,D))

[[4 1]
 [2 2]]


In [525]:
# Exercise 20: Flatten a 2D array to a 1D array
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B.flatten())

[1 2 3 4 5 6]


In [521]:
# Exercise 21: Stack two arrays vertically
E = np.array([1, 2, 3])
F = np.array([4, 5, 6])
print(np.vstack((E, F)))

[[1 2 3]
 [4 5 6]]


In [523]:
# Exercise 22: Stack two arrays horizontally
print(np.hstack((E, F)))

[1 2 3 4 5 6]


In [513]:
# Exercise 23: Split an array into multiple sub-arrays
G = np.array([1, 2, 3, 4, 5, 6])
print(np.split(G, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [511]:
# Exercise 24: Generate a random array and round to two decimal places
G = np.random.rand(5)
print(np.round(G, 2))

[0.17 0.12 0.13 0.08 0.19]


In [505]:
# Exercise 25: Find unique elements in an array
H = np.array([1, 2, 2, 3, 4, 4, 5])
print(np.unique(H))

[1 2 3 4 5]


In [503]:
# Exercise 26: Replace elements less than a value with that value
I = np.array([1, 5, 8, -3, -7, 9])
print(np.where(I < 0, 1, I))

[1 5 8 1 1 9]


In [499]:
# Exercise 27: Cumulative sum of elements in an array
I = np.array([1, 5, 8, -3, -7, 9])
print(np.cumsum(I))

[ 1  6 14 11  4 13]


In [497]:
# Exercise 28: Count non-zero elements in an array
I = np.array([1, 0, 8, -3, 0, 9])
print(np.count_nonzero(I))

4


In [495]:
# Exercise 29: Sort a random array of integers
J = np.random.randint(1, 100, size=10)
print(np.sort(J))

[20 40 41 60 61 69 86 87 88 99]


In [489]:
# Exercise 30: Row-wise and column-wise sum of a 3x3 matrix
J = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
row_sum = np.sum(J, axis=1)
col_sum = np.sum(J, axis=0)
print(row_sum, col_sum)

[ 6 15 24] [12 15 18]


In [487]:
# Exercise 31: Normalize a 2D array between 0 and 1
K = np.random.rand(3, 3)
normalz = (K - np.min(K)) / (np.max(K) - np.min(K))
print(normalz)

[[0.48356224 0.20216559 0.13890692]
 [0.         0.3069255  0.8779029 ]
 [0.02216911 0.74585837 1.        ]]


In [483]:
# Exercise 32: Dot product of two arrays
K = np.array([1, 2, 3])
L = np.array([4, 5, 6])
print(np.dot(K, L))

32


In [481]:
# Exercise 33: Find the trace of a square matrix
M = np.array([[1, 2], [3, 4]])
print(np.trace(M))

5


In [479]:
# Exercise 34: Swap two rows in a 2D array
N = np.array([[1, 2], [3, 4], [5, 6]])
N[[0, 1]] = N[[1, 0]]
print(N)

[[3 4]
 [1 2]
 [5 6]]


In [477]:
# Exercise 35: Convert a 1D array into a column vector
O = np.array([1, 2, 3])
print(O[:, np.newaxis])

[[1]
 [2]
 [3]]


In [475]:
# Exercise 36: Find the determinant of a 3x3 matrix
P = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print(np.linalg.det(P))

0.9999999999999987


In [473]:
# Exercise 37: Eigenvalues and eigenvectors of a 2x2 matrix
Q = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
print(eigenvalues,"\n", eigenvectors)

[ 3. -1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [469]:
# Exercise 38: Solve a system of linear equations
X = np.array([[3, 1], 
                 [1, 2]])
b = np.array([9, 8])
print(np.linalg.solve(X, b))

[2. 3.]


In [569]:
# Exercise 39: Add Gaussian noise to an array
R = np.array([1, 2, 3])
noise = np.random.normal(0, 0.1, R.shape)
print(R + noise)

[1.1478853  2.02178752 3.06230686]


In [467]:
# Exercise 40: Extract the diagonal elements of a 4x4 matrix
S = np.random.randint(1, 10, size=(4, 4))
print(np.diag(S))

[4 7 8 1]


In [465]:
# Exercise 41: Generate a random array of 100 values and clip between 10 and 50
A = np.random.randint(1, 100, size=100)
print(np.clip(A, 10, 50))

[50 50 50 50 31 32 27 14 45 50 20 10 50 10 35 50 50 10 31 50 50 27 50 32
 50 25 50 26 50 50 50 50 50 50 50 32 31 50 11 20 33 50 50 10 50 50 50 50
 10 50 10 50 36 50 26 50 10 18 10 10 26 22 19 37 11 50 50 50 16 50 21 50
 19 10 42 10 45 50 10 40 24 50 25 10 50 50 13 30 36 50 50 50 50 13 15 50
 10 13 41 45]


In [459]:
# Exercise 42: Replace negative values in a 2D array with zero
T = np.array([[1, -2, 3], [-4, 5, -6]])
print(np.where(T < 0, 0, T))

[[1 0 3]
 [0 5 0]]


In [457]:
# Exercise 43: Find the inner and outer products of two arrays
U = np.array([1, 2, 3])
V = np.array([4, 5, 6])
inner_p = np.inner(U, V)
outer_p = np.outer(U, V)
print(inner_p, outer_p)

32 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [565]:
# Exercise 44: Calculate pairwise distances between points in an array

In [567]:
# Exercise 45: Create a structured array with fields for name, age, and height

In [447]:
# Exercise 46: Count occurrences of each unique value in a 5x5 matrix
E = np.random.randint(0, 10, (5, 5))
unique, counts = np.unique(E, return_counts=True)
print(dict(zip(unique, counts)))

{2: 3, 3: 7, 4: 4, 5: 3, 6: 3, 7: 3, 8: 2}


In [439]:
# Exercise 47: Subtract the mean of each row from a 3x3 array
#A = np.random.rand(3, 3)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A - A.mean(axis=1))
A

[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [421]:
# Exercise 48: Check if any value in an array is greater than 50
W = np.random.randint(1, 100, size=10)
print(np.any(W > 50))

True


array([64, 84,  6, 65,  4, 65, 84, 26, 90, 96])

In [ ]:
# Exercise 49: Calculate the moving average of a 1D array

In [417]:
# Exercise 50 : Pearson correlation coefficient between two arrays
Y = np.array([1, 2, 3, 4, 5])
Z = np.array([5, 6, 7, 8, 7])
print(np.corrcoef(Y, Z)[0, 1])

0.8320502943378437


In [559]:
# Exercise 51: Convert a NumPy array of radians to degrees

In [557]:
# Exercise 52: Compute variance and standard deviation of a random array
M = np.random.rand(10)
variance = np.var(M)
std_dev = np.std(M)
print(variance, std_dev)

0.09583943067943948 0.30957944162918744


In [555]:
# Exercise 53: Find indices of maximum values along each axis in a 2D array
A = np.random.rand(3, 3)
maxr = np.argmax(A, axis=1) 
maxc = np.argmax(A, axis=0)  
print(maxr, maxc)

[1 0 1] [1 2 0]


In [549]:
# Exercise 54: Compute the inverse of a 2x2 matrix
I = np.array([[4, 7], [2, 6]])
print(np.linalg.inv(I))

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [545]:
# Exercise 55: Create a random array and standardize it (mean 0, variance 1)
A = np.random.rand(10)
standz = (A - np.mean(A)) / np.std(A)
print(standz)

[ 0.86119585 -1.74795093 -0.44069847 -0.86128612  1.0687897   1.27746688
  0.60699543 -0.23175513 -1.2483863   0.7156291 ]


In [541]:
# Exercise 56: Element-wise addition and subtraction of two arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A+B, A-B)

[5 7 9] [-3 -3 -3]


In [539]:
# Exercise 57: Find the index of the maximum element in an array
A = np.random.randint(100,size=(3,3))
np.argmax(A)

4

In [537]:
# Exercise 58: Rotate a 3x3 array by 90 degrees
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
np.rot90(A)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [535]:
# Exercise 59: Compute the Frobenius norm of a matrix
B = np.array([[1, 2], [3, 4]])
np.sqrt(np.trace(np.dot(B,B.T)))

5.477225575051661

In [ ]:
# Exercise 60: Slice out a subarray from a 3D array
A = np.random.randint(10, size=(3,3,3))
B = A[:1][:2][:3]
B